config/routes.rb
Rails.application.routes.draw do
  resources :tophundreds

  root 'home#index'

     get '/sum' => 'home#sum'
     get '/summult' => 'home#summult'
     get '/complex1' => 'home#complex1'

end

app/models/tophundred.rb
class Tophundred < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Home page for application
  def index
  end
  # This will be to gather the two values that will be added together
  # GET /summer
  # This will return the two values that you wanted added as well as the sum of the two
  # GET params[:val1] AND params[:val2] and return /sum
  def sum
    if params[:val1].blank? || params[:val2].blank?
      @val1 = 0
      @val2 = 0
    else
      @val1 = params[:val1].to_f
      @val2 = params[:val2].to_f
    end
  end

  def summult
    if params[:val1].blank? || params[:val2].blank?
      @val1 = 0
      @val2 = 0
    else
      @val1 = params[:val1].to_f
      @val2 = params[:val2].to_f
    end
  end

  def complex1
    if
      params[:val1].blank? || params[:val2].blank? || params[:val3].blank? || params[:val4].blank? || params[:val5].blank? || params[:val6].blank?
      @val1 = 0
      @val2 = 0
      @val3 = 0
      @val4 = 0
      @val5 = 0
      @val6 = 0
    else
      @val1 = params[:val1].to_f
      @val2 = params[:val2].to_f
      @val3 = params[:val3].to_f
      @val4 = params[:val4].to_f
      @val5 = params[:val5].to_f
      @val6 = params[:val6].to_f
    end
   end

  end

app/controllers/tophundreds_controller.rb
class TophundredsController < ApplicationController
  before_action :set_tophundred, only: [:show, :edit, :update, :destroy]

  # GET /tophundreds
  # GET /tophundreds.json
  def index
    @tophundreds = Tophundred.all
  end

  # GET /tophundreds/1
  # GET /tophundreds/1.json
  def show
  end

  # GET /tophundreds/new
  def new
    @tophundred = Tophundred.new
  end

  # GET /tophundreds/1/edit
  def edit
  end

  # POST /tophundreds
  # POST /tophundreds.json
  def create
    @tophundred = Tophundred.new(tophundred_params)

    respond_to do |format|
      if @tophundred.save
        format.html { redirect_to @tophundred, notice: 'Tophundred was successfully created.' }
        format.json { render :show, status: :created, location: @tophundred }
      else
        format.html { render :new }
        format.json { render json: @tophundred.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tophundreds/1
  # PATCH/PUT /tophundreds/1.json
  def update
    respond_to do |format|
      if @tophundred.update(tophundred_params)
        format.html { redirect_to @tophundred, notice: 'Tophundred was successfully updated.' }
        format.json { render :show, status: :ok, location: @tophundred }
      else
        format.html { render :edit }
        format.json { render json: @tophundred.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tophundreds/1
  # DELETE /tophundreds/1.json
  def destroy
    @tophundred.destroy
    respond_to do |format|
      format.html { redirect_to tophundreds_url, notice: 'Tophundred was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tophundred
      @tophundred = Tophundred.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tophundred_params
      params.require(:tophundred).permit(:genre, :songname, :artistname, :rank, :lyrics)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tophundreds_helper.rb
module TophundredsHelper
end

app/views/home/complex1.html.erb
<h2>Enter Six #'s'</h2>
<%= form_tag complex1_path, method: :get do %>
    <%=text_field_tag :val1 %>
     +
    <%=text_field_tag :val2 %>
     -
    <%=text_field_tag :val3 %>
     *
    <%=text_field_tag :val4 %>
     +
    <%=text_field_tag :val5 %>
     -
    <%=text_field_tag :val6 %>

    <%= submit_tag "Submit", name: nil %>

    <h2><%= @val1 %></h2>
    +
    <h2><%= @val2 %></h2>
    -
    <h2><%= @val3 %></h2>
    *
    <h2><%= @val4 %></h2>
    +
    <h2><%= @val5 %></h2>
    -
    <h2><%= @val6 %></h2>
    =
    <h1><%= (@val1 + @val2 - @val3) * (@val4 + @val5 - @val6) %></h1>
    <%= link_to "Try Again", complex1_path %>

<% end %>

app/views/home/index.html.erb
<h1>Welcome to Harmonic Trend Data Analysis</h1>
<%= link_to "HarmonicTrend.com", "http://www.HarmonicTrend.com" %>
<%= link_to "Top 100", tophundreds_path %>

app/views/home/sum.html.erb
<h2>Enter two #'s'</h2>
<%= form_tag sum_path, method: :get do %>
    <%= text_field_tag :val1 %>
     +
    <%=text_field_tag :val2 %>
    <%= submit_tag "Submit", name: nil %>

<h2><%= @val1 %></h2>
+
<h2><%= @val2 %></h2>
=
<h1><%= @val1 + @val2 %></h1>
<%= link_to "Try Again", sum_path %>

<% end %>

app/views/home/summult.html.erb
<h2>Enter two #'s'</h2>
<%= form_tag summult_path, method: :get do %>
    <%= text_field_tag :val1 %>
     *
    <%=text_field_tag :val2 %>
    <%= submit_tag "Submit", name: nil %>

<h2><%= @val1 %></h2>
*
<h2><%= @val2 %></h2>
=
<h1><%= @val1 * @val2 %></h1>
<%= link_to "Try Again", summult_path %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HarmonicTrend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tophundreds/_form.html.erb
<%= form_for(@tophundred) do |f| %>
  <% if @tophundred.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tophundred.errors.count, "error") %> prohibited this tophundred from being saved:</h2>

      <ul>
      <% @tophundred.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :songname %><br>
    <%= f.text_field :songname %>
  </div>
  <div class="field">
    <%= f.label :artistname %><br>
    <%= f.text_field :artistname %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tophundreds/edit.html.erb
<h1>Editing Tophundred</h1>

<%= render 'form' %>

<%= link_to 'Show', @tophundred %> |
<%= link_to 'Back', tophundreds_path %>

app/views/tophundreds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tophundreds</h1>

<table>
  <thead>
    <tr>
      <th>Genre</th>
      <th>Songname</th>
      <th>Artistname</th>
      <th>Rank</th>
      <th>Lyrics</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tophundreds.each do |tophundred| %>
      <tr>
        <td><%= tophundred.genre %></td>
        <td><%= tophundred.songname %></td>
        <td><%= tophundred.artistname %></td>
        <td><%= tophundred.rank %></td>
        <td><%= tophundred.lyrics %></td>
        <td><%= link_to 'Show', tophundred %></td>
        <td><%= link_to 'Edit', edit_tophundred_path(tophundred) %></td>
        <td><%= link_to 'Destroy', tophundred, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tophundred', new_tophundred_path %>
<%= link_to 'Go Home', root_path %>

app/views/tophundreds/new.html.erb
<h1>New Tophundred</h1>

<%= render 'form' %>

<%= link_to 'Back', tophundreds_path %>

app/views/tophundreds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre:</strong>
  <%= @tophundred.genre %>
</p>

<p>
  <strong>Songname:</strong>
  <%= @tophundred.songname %>
</p>

<p>
  <strong>Artistname:</strong>
  <%= @tophundred.artistname %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @tophundred.rank %>
</p>

<p>
  <strong>Lyrics:</strong>
  <%= @tophundred.lyrics %>
</p>

<%= link_to 'Edit', edit_tophundred_path(@tophundred) %> |
<%= link_to 'Back', tophundreds_path %>